language: c

cache:
  directories:
    - .cache

addons:
  apt:
    packages:
      - p7zip-full
      - python3-pip

jobs:
  include:
    - name: "Linux"
      dist: bionic
    - name: "macOS"
      os: osx
      osx_image: xcode11.3

before_install:
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install p7zip ; fi

install:
  - python3 --version
  - python3 -m pip --version
  - python3 -m pip install --upgrade pip
  - python3 -m pip install setuptools
  - python3 -m pip install amitools

script:
  - make clean
  - make buildenv   # cached
  - make
  - make release
  - unzip -lv *.zip
  - 7z h *.rom
