os:
  - windows
  - linux
  - osx
cache:
  directories:
    - .cache
addons:
  apt:
    packages:
      - p7zip-full
      - python-pip
  homebrew:
    packages:
      - p7zip
    update: true
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo easy_install pip; fi
  - sudo pip install amitools
script:
  - make clean
  - make
