language: c
#os:
#  - windows
#  - linux
#  - osx
cache:
  directories:
    - .cache
addons:
  apt:
    packages:
      - p7zip-full
      - python3-pip
  homebrew:
    packages:
      - p7zip
    update: true
  choco:
    packages:
      - python
      - sudo

matrix:
  include:
    - name: "Linux"
      os: linux
      python: 3.7
      before_install: python3 --version ; pip3 --version
    - name: "macOS"
      os: osx
      osx_image: xcode11
      language: shell
      before_install: python3 --version ; pip3 --version ; sw_vers
    - name: "Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version=3.7.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip3 install --upgrade pip
#install:
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo easy_install pip; fi
#  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python2 sudo make; fi
#  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then python -m pip install --upgrade pip; fi
  - pip install amitools
script:
  - make clean
  - make
