language: minimal
os:
  - windows
  - linux
  - osx
cache:
  directories:
    - .cache
addons:
  apt:
    packages:
      - p7zip-full
      - python-pip
install:
  - sudo pip install amitools
script:
  - make
