language: minimal
os:
  - windows
  - linux
  - osx
cache:
  directories:
    - .cache
addons:
  apt:
    packages:
      - p7zip-full
      - python-pip
  homebrew:
    packages:
      - p7zip
      - python
    update: true
install:
  - sudo pip install amitools
script:
  - make clean
  - make
