name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Linux:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: buildenv hash
      id: buildenv
      run: echo "::set-output name=sha::$(md5sum Makefile.build | cut -b-32)"
    - name: cache buildenv
      uses: actions/cache@v2
      id: cache-buildenv
      with:
        path: .cache
        key: ${{ runner.os }}-buildenv-${{ steps.buildenv.outputs.sha }}
    - name: install
      run: |
          python3 --version
          python3 -m pip --version
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools
          python3 -m pip install amitools
    - name: make clean
      run: make clean
    - name: make buildenv
      run: make buildenv
    - name: make
      run: make
    - name: make release
      run: make release
    - name: show zip contents
      run: unzip -lv *.zip
    - name: hash ROMs
      run: 7z h *.rom
    - name: show git status
      run: git status -s
      
    - uses: actions/upload-artifact@v2
      with:
        name: built_on_linux
        path: replay_rom_*.zip

  macOS:
  
    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v2
    - name: buildenv hash
      id: buildenv
      run: echo "::set-output name=hash::$(md5 -q Makefile.build)"
    - name: cache buildenv
      uses: actions/cache@v2
      id: cache-buildenv
      with:
        path: .cache
        key: ${{ runner.os }}-buildenv-${{ steps.buildenv.outputs.hash }}
    - name: install
      run: |
          python3 --version
          python3 -m pip --version
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools
          python3 -m pip install amitools
    - name: make clean
      run: make clean
    - name: make buildenv
      run: make buildenv
    - name: make
      run: make
    - name: make release
      run: make release
    - name: show zip contents
      run: unzip -lv *.zip
    - name: hash ROMs
      run: 7z h *.rom
    - name: show git status
      run: git status -s

    - uses: actions/upload-artifact@v2
      with:
        name: built_on_macos
        path: replay_rom_*.zip
